module.exports = [
  {
    _id: "127",
    images: [],
    name: "Clematis montana 'Rubens'",
    notes: "Likes full sun",
    latinName: "clematis montana",
    sowMonth: "",
    plantMonth: "April",
    flowerMonth: "June",
    pruneMonth: "",
    link: "",
    mainImage: "",
    createdAt: "2021-02-12T18:57:48.098+00:00",
  },
  {
    _id: "127",
    images: [],
    name: "Delphinium",
    notes: "Grow outdoors from seed",
    latinName: "delphinium",
    sowMonth: "March-April",
    plantMonth: "April",
    flowerMonth: "June",
    pruneMonth: "",
    link: "",
    mainImage: "",
    createdAt: "2021-02-12T18:57:48.098+00:00",
  },
];
